"""Constants for the Avocado Irrigation integration."""

DOMAIN = "avocado_irrigation"
NAME = "Avocado Irrigation"
VERSION = "0.1.0"

CONF_NAME = "name"

DEFAULT_NAME = "Avocado Irrigation"

# Initial defaults from the reference YAML implementation.
DEFAULT_WEEKLY_TARGET_MM = 12.0
DEFAULT_RAIN_EFFICIENCY = 0.75
DEFAULT_FLOW_RATE_MM_PER_MIN = 0.30
DEFAULT_DEEP_SOAK_TARGET_MM = 25.0
DEFAULT_PUMP_MIN_WATTS = 100.0
DEFAULT_DEEP_SOAK_MAX_RUNTIME_MIN = 120
DEFAULT_MAX_RUNTIME_MIN = 60
DEFAULT_ROUTINE_DRYDOWN_DAYS = 4.0
DEFAULT_DEEP_SOAK_DRYDOWN_DAYS = 8.0
DEFAULT_DEEP_SOAK_RAIN_THRESHOLD_MM = 40.0
DEFAULT_HOT_TEMPERATURE_C = 31.5

SIGNIFICANT_RAIN_24H_MM = 35.0
SIGNIFICANT_RAIN_4D_MM = 50.0
SIGNIFICANT_RAIN_7D_MM = 100.0

ROUTINE_INTERVAL_COOL_DAYS = 4
ROUTINE_INTERVAL_HOT_DAYS = 3
